
-- --------------------------------------------------------

--
-- Table structure for table `spellsstates`
--

CREATE TABLE `spellsstates` (
  `Id` int(40) NOT NULL DEFAULT '0',
  `Name` mediumtext,
  `PreventsSpellCast` mediumtext,
  `PreventsFight` mediumtext,
  `IsSilent` mediumtext,
  `CantBeMoved` mediumtext,
  `CantBePushed` mediumtext,
  `CantDealDamage` mediumtext,
  `Invulnerable` mediumtext,
  `CanSwitchPosition` mediumtext,
  `Incurable` mediumtext,
  `InvulnerableMelee` mediumtext,
  `InvulnerableRange` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `spellsstates`
--

INSERT INTO `spellsstates` (`Id`, `Name`, `PreventsSpellCast`, `PreventsFight`, `IsSilent`, `CantBeMoved`, `CantBePushed`, `CantDealDamage`, `Invulnerable`, `CanSwitchPosition`, `Incurable`, `InvulnerableMelee`, `InvulnerableRange`) VALUES
(0, 'Neutre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(1, 'Saoul', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(2, 'Chercheur d âmes', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(3, 'Porteur', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(4, 'Peureux', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(5, 'Désorienté', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(6, 'Enraciné', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'True', 'False', 'False', 'False'),
(7, 'Pesanteur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(8, 'Porté', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(9, 'Motivation Sylvestre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(10, 'Apprivoisement', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(11, 'Chevauchant', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(12, 'Pas sage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(13, 'Vraiment pas sage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(14, 'Enneigé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(15, 'Eveillé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(16, 'Fragilisé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(17, 'Séparé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(18, 'Gelé', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(19, 'Fissuré', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(26, 'Endormi', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(27, 'Léopardo', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(28, 'Libre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(29, 'Glyphe impaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(30, 'Glyphe paire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(31, 'Encre primaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(32, 'Encre secondaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(33, 'Encre tertiaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(34, 'Encre quaternaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(35, 'Envie de tuer', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(36, 'Envie de paralyser', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(37, 'Envie de maudire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(38, 'Envie d empoisonner', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(39, 'Flou', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(40, 'Corrompu', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(41, 'Silencieux', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(42, 'Affaibli', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(43, 'OVNI', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(44, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(46, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(47, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(48, 'Confus', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(49, 'Goulifié', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(50, 'Décisif', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(51, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(52, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(53, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(54, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(55, 'Retraité', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(56, 'Invulnérable', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(57, 'Compte à rebours - 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(58, 'Compte à rebours - 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(60, 'Dévoué', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(61, 'Bagarreur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(63, 'Lourd', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(64, 'Glyphangueur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(65, 'Oméga', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(66, 'Alpha', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(67, 'Bêta', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(68, 'Gamma', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(69, 'Delta', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(70, 'Alpha de Kordis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(71, 'Bêta de Kordis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(72, 'Gamma de Kordis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(73, 'Enragé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(74, 'Zombi', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(76, 'Insoignable', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False'),
(77, 'Faiblesse', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(78, 'Germe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(79, 'Seconde', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(80, 'Tierce', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(81, 'Quarte', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(82, 'Quinte', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(83, 'Sixte', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(84, 'Septième', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(85, 'Octave', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(86, 'Fulguration', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(87, 'Floutage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(88, 'Résuglours', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(89, 'Flamboyant', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(90, 'Ectoplasmique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(91, 'Ardent', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(92, 'Kaboom', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(93, 'Fonso Cacnoob', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(94, 'Pacette Foinoube', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(95, 'Intacleur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(96, 'Intaclable', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(97, 'Indéplaçable', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(98, 'Classe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(99, 'Psychopathe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(100, 'Pleutre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(101, 'Archer', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(102, 'Gorgouillis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(103, 'Fortifié', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(104, 'Rupture', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(105, 'Tyrannisé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(106, 'Météoroïde', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(107, 'Masse Critique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(108, 'Apocalypse', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(109, 'Rubilax', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(110, '« L Épée »', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(111, 'Première Marque de Daïgoro', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(112, 'Deuxième Marque de Daïgoro', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(113, 'Troisième Marque de Daïgoro', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(114, 'Quatrième Marque de Daïgoro', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(115, 'Cinquième Marque de Daïgoro', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(116, 'Vert de Terre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(117, 'Rose aux Flammes', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(118, 'Azur Bain', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(119, 'Ex Jaune Air', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(120, 'Déplacé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(121, 'Charge', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(122, 'Décharge', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(123, 'Surcharge', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(124, 'Grand Frère', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(125, 'Petite Sœur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(126, 'Magnétor', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(127, 'Tellurique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(128, 'Aquatique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(129, 'Ardent', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(130, 'Embuscade', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(131, 'Secourisme', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(132, 'Longue vue', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(133, 'Cuirasse', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(134, 'Evolution II', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(135, 'Evolution III', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(136, 'Endeuillé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(137, 'Kwaflamme', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(138, 'Kwaglace', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(139, 'Kwaterre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(140, 'Kwavent', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(141, 'Kwaneutre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(142, 'Pandawushae', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(143, 'Pandawushak', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(144, 'Pandawushfe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(145, 'Pandawushte', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(146, 'Pandawushne', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(147, 'Courte vue', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(148, 'Corselet', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(149, 'Dingue', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(150, 'Emberlificoté', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(151, 'Précipité', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(152, 'Peau lisse', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(153, 'Surgelé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(154, 'Renaissance', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(155, 'Zombidule', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(156, 'Thermolacté', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(157, 'Inébranlable', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False'),
(158, 'Marionnette', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(159, 'Acte 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(160, 'Acte 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(161, 'Acte 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(162, 'Acte 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(163, 'Acte 5', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(164, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(165, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(166, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(167, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(168, 'Pentacle', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(169, 'Bruyant', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(170, 'Acte 6', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(171, 'Foudroyé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(172, 'Empathique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(173, 'Parasite granuleux', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(174, 'Parasite éclos', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(175, 'Parasite fleuri', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(176, 'Friture', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(177, 'Poulpé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(178, 'Araknophobe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(179, 'Androphobe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(180, 'Araneae', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(181, 'Misandrie', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(182, 'Chargé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(183, 'Scorifié', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(184, 'Protégé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(185, 'Trop Saoul', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(186, 'Courageux', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(187, 'Veinard', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(188, 'Redirection', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(189, 'Mal des transports', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(190, 'Tumvoipu', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(191, 'Marque des Mangelors', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(192, 'Coffrage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(193, 'Glyphor', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(194, 'Seul', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(195, 'Mèche courte', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(196, 'Mèche longue', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(197, 'Mort en sursis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(198, 'Désamorcée', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(199, 'Marqueur Chimique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(200, 'Sang', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(201, 'Sel', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(202, 'Or', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(203, 'Jouvence', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(204, 'Indulgent I', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(205, 'Indulgent II', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(206, 'Indulgent III', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(207, 'Indulgent IV', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(208, 'Indulgent V', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(209, 'Indulgent VI', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(210, 'Indulgent VII', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(211, 'Indulgent VIII', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(212, 'Indulgent IX', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(213, 'Indulgent X', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(214, 'Disloqué', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(215, 'Infection', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(216, 'Passeur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(217, 'Temporisateur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(218, 'Pacifiste', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False'),
(219, 'Voyageur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(220, 'Instable', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(221, 'Première heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(222, 'Deuxième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(223, 'Troisième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(224, 'Quatrième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(225, 'Cinquième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(226, 'Sixième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(227, 'Septième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(228, 'Huitième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(229, 'Neuvième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(230, 'Dixième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(231, 'Onzième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(232, 'Douzième heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(233, 'Mort latente', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(234, 'Même heure', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(235, 'Tueur', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(236, 'Marginal', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(237, 'Dérèglement', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(238, 'Hypoglyphe', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(239, 'Bien entouré', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(240, 'Résurrection', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(241, 'Sérum', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(242, 'Passtontour', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(243, 'Coffre invoqué', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(244, 'Téléfrag', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(245, 'Momie', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(246, 'Paradoxe temporel', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(247, 'Rembobinage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(248, 'Portail', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(249, 'Immunité temporelle', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(250, 'Invisible', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(251, 'Téléfrag', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(252, 'Emprisonné', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(253, 'Cocon', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(254, 'Maturité', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(255, 'Dévoué', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(256, 'Arbre Feuillu', 'False', 'False', 'True', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False'),
(257, 'Amour infini', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False'),
(258, 'Marque Ninja', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(259, 'Bloqueuse', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(260, 'Écologiste', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(261, 'Écologiste', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(262, 'Cible du Super placement', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(263, 'Infecté', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(264, 'Empoisonné', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(265, 'Proie', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(266, 'Bretteur Céleste', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(267, 'Foudroyé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(268, 'Duel', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(269, 'Invulnérable', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(270, 'Super Singe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(271, 'Rayonnement lunaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(272, 'Feu de Bolgrot', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(273, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(274, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(275, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(276, 'Etat générique 4', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(277, 'Etat générique 3', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(278, 'Etat générique 2', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(279, 'Etat générique 1', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(280, 'Transcendance Spirituelle', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(281, 'Amélioré', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(282, 'Goémus', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(283, 'Norie', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(284, 'Kelpe', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(285, 'Cyanog', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(286, 'Verak', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(287, 'Explosif', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(288, 'Immunité', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(289, '', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(290, 'Feu', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(291, 'Eau', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(292, 'Terre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(293, 'Air', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(294, '', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(295, 'Soin glyphe', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(296, 'Rune', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(297, 'Muta', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(298, 'Djim', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(299, 'Ultram', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(300, 'Markalakulote', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(301, 'Reculpa', 'False', 'False', 'False', 'True', 'True', 'False', 'False', 'True', 'False', 'False', 'False'),
(302, 'Pierre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(303, 'Feuille', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(304, 'Ciseaux', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(305, 'Chassé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(306, 'Synchronisé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(307, 'Maudit', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(308, 'Collé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(309, 'Affaiblissement Aquatique', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(310, 'Affaiblissement Incandescent', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(311, 'Affaiblissement Venteux', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(312, 'Affaiblissement Terrestre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(313, 'Dé 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(314, 'Dé 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(315, 'Dé 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(316, 'Dé 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(317, 'Dé 5', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(318, 'Dé 6', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(324, 'Rouge', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(325, 'Noir', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(326, 'Dé 1 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(327, 'Dé 2 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(328, 'Dé 3 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(329, 'Dé 4 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(330, 'Dé 5 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(331, 'Dé 6 bis', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(332, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(333, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(334, 'Mutation I', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(335, 'Mutation II', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(336, 'Mutation III', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(337, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(338, 'Vewwouillé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(339, 'Pourrification', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(340, 'Poutrage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(341, 'Etat générique 5', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(342, 'Etat générique 6', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(343, 'Etat générique 7', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(344, 'Etat générique 8', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(345, 'Etat générique 9', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(346, 'Chaloeil - Blanc', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(347, 'Chaloeil - Noir', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(348, 'Matoumorphose', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(349, 'Stimulé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(350, '', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(351, 'Telefrag Rayon Obscur', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(352, 'Telefrag Téléportation', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(353, 'Telefrag Rembobinage', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(354, 'Telefrag Poussière', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(355, 'Telefrag Raulebaque', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(356, 'Telefrag Gelure', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(357, 'Telefrag Fuite', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(358, 'Telefrag Paradoxe', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(359, 'Telefrag Frappe', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(360, 'Telefrag Téléportation', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(361, 'Contribution', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(362, 'Parpo allié', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(363, 'Parpo ennemi', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(364, 'Transko', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(365, 'Invulnérable', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(366, 'Imunité - Chaloeil', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(367, 'Dé 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(368, 'Dé 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(369, 'Dé 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(370, 'Dé 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(371, 'Dé 5', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(372, 'Dé 6', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(373, 'Relance - Chaloeil', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(374, 'Matoumorphose', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(375, 'Invulnérabilité à Distance', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'True'),
(376, 'Invulnérabilité en Mêlée', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False'),
(377, 'Matoumorphose', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(378, 'Parasité', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(379, 'Indéplaçable', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(380, 'C est toi le Chacha !', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(381, 'Cible prioritaire', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(382, 'Intercepteur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(383, 'Protégé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(384, 'Embargo', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(385, 'Air Eniripsatest', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(386, 'Phuan', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(387, 'Stimulé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(388, 'Cauchemar', 'False', 'False', 'False', 'True', 'True', 'False', 'True', 'True', 'False', 'False', 'False'),
(389, 'Halluciné', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(390, 'Premier Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(391, 'Second Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(392, 'Troisième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(393, 'Quatrième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(394, 'Cinquième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(395, 'Sixième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(396, 'Septième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(397, 'Huitième Grokillage', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(398, 'Marché Conclus', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(399, 'Invulnérable', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False'),
(400, 'Folie 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(401, 'Folie 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(402, 'Folie 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(403, 'Folie 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(404, 'Folie 5', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(405, 'Folie 6', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(406, 'Folie 7', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(407, 'Folie 8', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(408, 'Folie 9', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(409, 'Lié', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(410, 'Conducteur', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(411, 'Mutation I', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(412, 'Mutation II', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(413, 'Mutation III', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(414, 'Apprivoisable', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(415, 'Muldo Pourpre', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(416, 'Ansôhterie', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'True', 'False', 'False', 'False'),
(417, 'Takomako', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(418, 'Céphalogre', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(419, 'Mal d Invocation', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(420, 'Solo', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(421, 'Duo', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(422, 'Draché', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(423, 'Trio', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(424, 'Terpané', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(425, 'Dofus Abyssal', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(426, 'Panne', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(427, 'Apprivoisement Cheat', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(428, 'Rancunier', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(429, 'Surnombre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(430, 'Outils', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(431, 'Homard Medali', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(432, 'Transformation Tofu', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(433, 'Transformation Bouftou', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(434, 'Transformation Dragonnet', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(435, 'Tranche Air', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(436, 'Dragosoin', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(437, 'Rancune', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False');
INSERT INTO `spellsstates` (`Id`, `Name`, `PreventsSpellCast`, `PreventsFight`, `IsSilent`, `CantBeMoved`, `CantBePushed`, `CantDealDamage`, `Invulnerable`, `CanSwitchPosition`, `Incurable`, `InvulnerableMelee`, `InvulnerableRange`) VALUES
(438, 'Liberté', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False'),
(439, 'Symbiose', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(440, 'Ciblé', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(441, 'Tactique A', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(442, 'Tactique B', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(443, 'Tactique C', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(444, 'Tactique D', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(445, 'Fixé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(446, 'Transposition', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(447, 'Lien animal', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(448, 'Sursis', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(449, 'Vulnérable', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(450, 'Cacterrorisé', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(451, 'Tofu invoqué', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(452, 'Bouftou invoqué', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(453, 'Dragonnet invoqué', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(454, 'Eteint', 'False', 'False', 'True', 'True', 'False', 'False', 'False', 'True', 'False', 'False', 'False'),
(455, 'Tour 1', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(456, 'Tour 2', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(457, 'Tour 3', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(458, 'Tour 4', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(459, 'Tour 5', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(460, 'Tour 6', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(461, 'Tour 7', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(462, 'Tour 8', 'False', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(463, 'Cellule 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(464, 'Cellule 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(465, 'Cellule 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(466, 'Cellule 1', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(467, 'Cellule 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(468, 'Cellule 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(469, 'Cellule 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(470, 'Cellule 2', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(471, 'Cellule 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(472, 'Cellule 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(473, 'Cellule 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(474, 'Cellule 3', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(475, 'Cellule 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(476, 'Cellule 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(477, 'Cellule 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(478, 'Cellule 4', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(479, 'Feu', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(480, 'Eau', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(481, 'Air', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False'),
(482, 'Terre', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False');
