
-- --------------------------------------------------------

--
-- Table structure for table `titles`
--

CREATE TABLE `titles` (
  `Id` int(40) NOT NULL DEFAULT '0',
  `NameMale` mediumtext,
  `NameFemale` mediumtext,
  `CategoryId` mediumtext,
  `Visible` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `titles`
--

INSERT INTO `titles` (`Id`, `NameMale`, `NameFemale`, `CategoryId`, `Visible`) VALUES
(1, 'Goule', 'Goule', '9', 'False'),
(2, 'Vampyre', 'Vampyre', '9', 'False'),
(3, 'Vampyre Sanglant', 'Vampyre Sanglante', '9', 'False'),
(4, 'Vampyre Maudyt', 'Vampyre Maudyte', '9', 'False'),
(5, 'Vampyre Ultyme', 'Vampyre Ultyme', '9', 'False'),
(6, 'Vampyre Démonyaque', 'Vampyre Démonyaque', '9', 'False'),
(7, 'Vampyre Runyque', 'Vampyre Runyque', '9', 'False'),
(8, 'Pourfendeur de Bworker', 'Pourfendeuse de Bworker', '6', 'False'),
(9, 'Pourfendeur du Sphincter Cell', 'Pourfendeuse du Sphincter Cell', '6', 'False'),
(10, 'Pourfendeur du Koulosse', 'Pourfendeuse du Koulosse', '6', 'False'),
(11, 'Pourfendeur du Wa Wabbit', 'Pourfendeuse du Wa Wabbit', '6', 'False'),
(12, 'Pourfendeur du Kimbo', 'Pourfendeuse du Kimbo', '6', 'False'),
(13, 'Pourfendeur du Minotoror', 'Pourfendeuse du Minotoror', '6', 'False'),
(14, 'Pourfendeur du Dragon Cochon', 'Pourfendeuse du Dragon Cochon', '6', 'False'),
(15, 'Pourfendeur du Chêne Mou', 'Pourfendeuse du Chêne Mou', '6', 'False'),
(16, 'Pourfendeur du Moon', 'Pourfendeuse du Moon', '6', 'False'),
(17, 'Pourfendeur du Dark Vlad', 'Pourfendeuse du Dark Vlad', '6', 'False'),
(18, 'Héros Bicentenaire', 'Héroïne Bicentenaire', '5', 'False'),
(19, 'Chevalier HispaÑique', 'Chevalier HispaÑique', '5', 'False'),
(20, 'Terreur de la Presqu île', 'Terreur de la Presqu île', '7', 'True'),
(21, 'Dékrokilliseur', 'Dékrokilliseuse', '7', 'True'),
(22, 'Bûcheron Primordial', 'Bûcheronne Primordiale', '4', 'False'),
(23, 'Forgeur d Epées Primordial', 'Forgeuse d Epées Primordiale', '4', 'False'),
(24, 'Sculpteur d Arcs Primordial', 'Sculpteuse d Arcs Primordiale', '4', 'False'),
(25, 'Forgeur de Marteaux Primordial', 'Forgeuse de Marteaux Primordiale', '4', 'False'),
(26, 'Cordonnier Primordial', 'Cordonnière Primordiale', '4', 'False'),
(27, 'Bijoutier Primordial', 'Bijoutière Primordiale', '4', 'False'),
(28, 'Forgeur de Dagues Primordial', 'Forgeuse de Dagues Primordiale', '4', 'False'),
(29, 'Sculpteur de Bâtons Primordial', 'Sculpteuse de Bâtons Primordiale', '4', 'False'),
(30, 'Sculpteur de Baguettes Primordial', 'Sculpteuse de Baguettes Primordiale', '4', 'False'),
(31, 'Forgeur de Pelles Primordial', 'Forgeuse de Pelles Primordiale', '4', 'False'),
(32, 'Mineur Primordial', 'Mineuse Primordiale', '4', 'False'),
(33, 'Boulanger Primordial', 'Boulangère Primordiale', '4', 'False'),
(34, 'Alchimiste Primordial', 'Alchimiste Primordiale', '4', 'False'),
(35, 'Tailleur Primordial', 'Tailleuse Primordiale', '4', 'False'),
(36, 'Paysan Primordial', 'Paysanne Primordiale', '4', 'False'),
(37, 'Forgeur de Haches Primordial', 'Forgeuse de Haches Primordiale', '4', 'False'),
(38, 'Pêcheur Primordial', 'Pêcheuse Primordiale', '4', 'False'),
(39, 'Chasseur Primordial', 'Chasseuse Primordiale', '4', 'False'),
(40, 'Forgemage de Dagues Primordial', 'Forgemage de Dagues Primordiale', '4', 'False'),
(41, 'Forgemage d Epées Primordial', 'Forgemage d Epées Primordiale', '4', 'False'),
(42, 'Forgemage de Marteaux Primordial', 'Forgemage de Marteaux Primordiale', '4', 'False'),
(43, 'Forgemage de Pelles Primordial', 'Forgemage de Pelles Primordiale', '4', 'False'),
(44, 'Forgemage de Haches Primordial', 'Forgemage de Haches Primordiale', '4', 'False'),
(45, 'Sculptemage d Arcs Primordial', 'Sculptemage d Arcs Primordiale', '4', 'False'),
(46, 'Sculptemage de Baguettes Primordial', 'Sculptemage de Baguettes Primordiale', '4', 'False'),
(47, 'Sculptemage de Bâtons Primordial', 'Sculptemage de Bâtons Primordiale', '4', 'False'),
(48, 'Boucher Primordial', 'Bouchère Primordiale', '4', 'False'),
(49, 'Poissonnier Primordial', 'Poissonnière Primordiale', '4', 'False'),
(50, 'Forgeur de Boucliers Primordial', 'Forgeuse de Boucliers Primordiale', '4', 'False'),
(51, 'Cordomage Primordial', 'Cordomage Primordiale', '4', 'False'),
(52, 'Joaillomage Primordial', 'Joaillomage Primordials', '4', 'False'),
(53, 'Costumage Primordial', 'Costumage Primordiale', '4', 'False'),
(54, 'Bricoleur Primordial', 'Bricoleuse Primordiale', '4', 'False'),
(55, 'Pourfendeur des congères', 'Pourfendeuse des congères', '8', 'False'),
(56, 'Nettoyeur de donjon', 'Nettoyeuse de donjon', '8', 'False'),
(57, 'Maudit par Az le Tech', 'Maudite par Az le Tech', '1', 'False'),
(58, 'Maître des Éléments', 'Maîtresse des Éléments', '1', 'True'),
(59, 'Grand Maître des Éléments', 'Grande Maîtresse des Éléments', '1', 'True'),
(60, 'Initié du S.L.I.P.', 'Initiée du S.L.I.P.', '1', 'True'),
(61, 'Conquérant de la Lumière', 'Conquérante de la Lumière', '1', 'True'),
(62, 'Popol le Poulpe', 'Popol le Poulpe', '8', 'False'),
(63, 'Noweliste', 'Noweliste', '7', 'True'),
(64, 'Ballotin', 'Ballotin', '7', 'True'),
(65, 'Ballotine', 'Ballotine', '7', 'True'),
(66, 'Coeur à prendre', 'Coeur à prendre', '7', 'True'),
(67, 'Grand Stratéglours', 'Grande Stratéglourse', '8', 'False'),
(68, 'Marcheur Dimensionnel', 'Marcheuse Dimensionnelle', '9', 'False'),
(69, 'Apprenti d Otomaï', 'Apprentie d Otomaï', '1', 'True'),
(70, 'Champion du Goultarminator 639', 'Championne du Goultarminator 639', '8', 'False'),
(71, 'Mister Amakna', 'Mister Amakna', '8', 'False'),
(72, 'Miss Amakna', 'Miss Amakna', '8', 'False'),
(73, 'Mister Monde des Douze', 'Mister Monde des Douze', '8', 'False'),
(74, 'Miss Monde des Douze', 'Miss Monde des Douze', '8', 'False'),
(75, 'Chasseur de Touristes', 'Chasseuse de Touristes', '7', 'True'),
(76, 'Chasseur de Krokilles', 'Chasseuse de Krokilles', '7', 'True'),
(77, 'Chasseur de Légendes', 'Chasseuse de Légendes', '7', 'True'),
(78, 'Héroe de HispaÑia', 'Héroe de HispaÑia', '5', 'False'),
(79, 'Chercheur de Dofus', 'Chercheuse de Dofus', '1', 'True'),
(80, 'Marque-Page', 'Marque-Page', '1', 'True'),
(81, 'Champion du Goultarminator 640', 'Championne du Goultarminator 640', '8', 'False'),
(82, 'Champion du Goultarminator 641', 'Championne du Goultarminator 641', '8', 'False'),
(83, 'Terreur de Vulkania', 'Terreur de Vulkania', '7', 'True'),
(84, 'Noweliste Grandiloquent', 'Noweliste Grandiloquente', '7', 'True'),
(85, 'Noweliste Décadent', 'Noweliste Décadente', '7', 'True'),
(86, 'Disciple Pandawushuka', 'Disciple Pandawushuka', '1', 'True'),
(87, 'Champion Azur', 'Championne Azur', '5', 'False'),
(89, 'Protecteur des Profondeurs', 'Protectrice des Profondeurs', '8', 'False'),
(90, 'Pwâkificateur', 'Pwâkificatrice', '8', 'True'),
(91, 'Robill Adoptif', 'Robill Adoptive', '1', 'True'),
(93, 'Trouffion des Neiges', 'Trouffion des Neiges', '1', 'True'),
(94, 'Commère des Miches', 'Commère des Miches', '1', 'True'),
(95, 'Pilier de Comptoir', 'Pilier de Comptoir', '5', 'False'),
(96, 'Mini-Mister Amakna', 'Mini-Mister Amakna', '8', 'False'),
(97, 'Mini-Miss Amakna', 'Mini-Miss Amakna', '8', 'False'),
(98, 'Écumeur des 107 océans', 'Écumeuse des 107 océans', '7', 'False'),
(99, 'Farfouilleur d Otomaï', 'Farfouilleuse d Otomaï', '9', 'False'),
(100, 'Citrouillard', 'Citrouillarde', '7', 'True'),
(101, 'Champion du Goultarminator 642', 'Championne du Goultarminator 642', '8', 'False'),
(102, 'Chevalier Doré HispaÑique', 'Chevalier Doré HispaÑique', '5', 'False'),
(103, 'Ami de Kerubim', 'Amie de Kerubim', '1', 'True'),
(109, 'La Machine', 'La Machine', '1', 'True'),
(110, 'Accoucheur survolté', 'Accoucheuse survoltée', '1', 'True'),
(111, 'Colosse aux pieds graciles', 'Colosse aux pieds graciles', '1', 'True'),
(112, 'Aventurier de l Avent', 'Aventurière de l Avent', '7', 'True'),
(113, 'Émotif', 'Émotive', '1', 'True'),
(114, 'Tête Couronnée', 'Tête Couronnée', '1', 'True'),
(115, 'Moissonneur des Âmes', 'Moissonneuse des Âmes', '1', 'True'),
(116, 'Héros de l Année', 'Héroïne de l Année', '1', 'True'),
(117, 'Chasseur de Primes', 'Chasseuse de Primes', '1', 'True'),
(118, 'Chahuteur Clandestin', 'Chahuteuse Clandestine', '1', 'True'),
(119, 'Querelleur Clandestin', 'Querelleuse Clandestine', '1', 'True'),
(120, 'Bagarreur Clandestin', 'Bagarreuse Clandestine', '1', 'True'),
(121, 'Lutteur Clandestin', 'Lutteuse Clandestine', '1', 'True'),
(122, 'Combattant Clandestin', 'Combattante Clandestine', '1', 'True'),
(123, 'Champion Clandestin', 'Championne Clandestine', '1', 'True'),
(124, 'Lécheur de Bottes', 'Lécheuse de Bottes', '1', 'True'),
(125, 'Bouche-trou', 'Bouche-trou', '1', 'True'),
(126, 'Krosmonaute', 'Krosmonaute', '1', 'True'),
(128, 'Enquêteur', 'Enquêteuse', '1', 'True'),
(129, 'Chercheur de Vérité', 'Chercheuse de Vérité', '1', 'True'),
(130, 'Marabout', 'Marabout', '1', 'True'),
(134, 'Garde du Jour sans Fin', 'Garde du Jour sans Fin', '1', 'True'),
(135, 'Bienfaiteur de Frigost', 'Bienfaitrice de Frigost', '1', 'True'),
(136, 'Vengeur des Terres Gelées', 'Vengeresse des Terres Gelées', '1', 'True'),
(139, 'Poursuivant de Mythes', 'Poursuivante de Mythes', '1', 'True'),
(140, 'Jouet des Immortels', 'Jouet des Immortels', '1', 'True'),
(142, 'Larve de Dremoan', 'Larve de Dremoan', '1', 'True'),
(143, 'Collectionneur de trucs', 'Collectionneuse de trucs', '1', 'True'),
(144, 'Éclaireur d Obscurité', 'Éclaireuse d Obscurité', '8', 'True'),
(145, 'Cwoqueuw de Cawotte', 'Cwoqueuse de Cawotte', '1', 'True'),
(146, 'Nettoyeur de Shushu', 'Nettoyeuse de Shushu', '1', 'True'),
(147, 'Super-assistant', 'Super-assistante', '1', 'True'),
(148, 'Champion du Goultarminator 643', 'Championne du Goultarminator 643', '8', 'False'),
(149, 'Gardien de la Paix', 'Gardienne de la Paix', '1', 'True'),
(150, 'Terreur des Mercemers', 'Terreur des Mercemers', '1', 'True'),
(151, 'Justicier du Krosmoz', 'Justicière du Krosmoz', '1', 'True'),
(152, 'Héros costumé', 'Héroïne costumée', '1', 'True'),
(153, 'Perceur de Mystères', 'Perceuse de Mystères', '1', 'True'),
(154, 'Déjoueur de Pièges', 'Déjoueuse de Pièges', '8', 'True'),
(155, 'Agent de Voyage', 'Agent de Voyage', '1', 'True'),
(156, 'Senior d Enutrosor', 'Senior d Enutrosor', '1', 'True'),
(157, 'Baron de la Cour Sombre', 'Baronne de la Cour Sombre', '1', 'True'),
(158, 'Vagabond Dimensionnel', 'Vagabonde Dimensionnelle', '1', 'True'),
(159, 'Champion du Goultarminator 644', 'Championne du Goultarminator 644', '8', 'False'),
(160, 'Défenseur de la Nature', 'Défenseur de la Nature', '1', 'True'),
(161, 'Ouvreur de Portail', 'Ouvreuse de Portail', '1', 'True'),
(162, 'Gardien du Xélorium', 'Gardienne du Xélorium', '1', 'True'),
(163, 'Rmyfau qub usywrub', 'Rmyfaubbu qub usywrub', '5', 'True'),
(164, 'Investigateur obstiné', 'Investigatrice obstinée', '1', 'True'),
(165, 'Batailleur', 'Batailleuse', '7', 'True'),
(166, 'Traqueur Implacable', 'Traqueuse Implacable', '1', 'True'),
(167, 'Disciple de Menalt', 'Disciple de Menalt', '10', 'False'),
(168, 'Écuyer', 'Écuyère', '10', 'False'),
(169, 'Chevalier de l Espoir', 'Chevalière de l Espoir', '10', 'False'),
(170, 'Champion Merveilleux', 'Championne Merveilleuse', '10', 'False'),
(172, 'Disciple de Jiva', 'Disciple de Jiva', '10', 'False'),
(173, 'Apprenti Éclairé', 'Apprentie Éclairée', '10', 'False'),
(174, 'Adepte des Écrits', 'Adepte des Écrits', '10', 'False'),
(175, 'Maître des Parchemins', 'Maîtresse des Parchemins', '10', 'False'),
(177, 'Disciple de Silvosse', 'Disciple de Silvosse', '10', 'False'),
(178, 'Espion Silencieux', 'Espionne Silencieuse', '10', 'False'),
(179, 'Chasseur de Renégats', 'Chasseuse de Renégats', '10', 'False'),
(180, 'Assassin Suprême', 'Assassin Suprême', '10', 'False'),
(182, 'Disciple de Djaul', 'Disciple de Djaul', '10', 'False'),
(183, 'Surineur', 'Surineuse', '10', 'False'),
(184, 'Chevalier du Désespoir', 'Chevalière du Désespoir', '10', 'False'),
(185, 'Champion du Chaos', 'Championne du Chaos', '10', 'False'),
(187, 'Disciple d Hécate', 'Disciple d Hécate', '10', 'False'),
(188, 'Apprenti Sombre', 'Apprentie Sombre', '10', 'False'),
(189, 'Adepte des Douleurs', 'Adepte des Douleurs', '10', 'False'),
(190, 'Maître des Sévices', 'Maîtresse des Sévices', '10', 'False'),
(192, 'Disciple de Brumaire', 'Disciple de Brumaire', '10', 'False'),
(193, 'Espion Sombre', 'Espionne Sombre', '10', 'False'),
(194, 'Chasseur d Âmes', 'Chasseuse d Âmes', '10', 'False'),
(195, 'Psychopathe', 'Psychopathe', '10', 'False'),
(197, 'Fils d Incarnam', 'Fille d Incarnam', '1', 'True'),
(198, 'Champion du Goultarminator 645', 'Championne du Goultarminator 645', '8', 'False'),
(199, 'Idole des jeunes', 'Idole des jeunes', '1', 'True'),
(200, 'Allié de Joris', 'Alliée de Joris', '1', 'True'),
(201, 'Maître du Chifoumi', 'Maîtresse du Chifoumi', '1', 'True'),
(202, 'Vainqueur des 1001 Griffes', 'Vainqueure des 1001 Griffes', '8', 'False'),
(203, 'Joueur professionnel', 'Joueuse professionnelle', '1', 'True'),
(204, 'Perfectionniste', 'Perfectionniste', '1', 'True'),
(205, 'Seigneur des Embruns', 'Dame des Embruns', '1', 'True'),
(206, 'Koutoulou Fhtagn', 'Koutoulou Fhtagn', '1', 'True'),
(207, 'Roi de la Plonge', 'Reine de la Plonge', '1', 'True'),
(208, 'Trithonite', 'Trithonite', '1', 'True'),
(209, 'Champion du Goultarminator 646', 'Championne du Goultarminator 646', '8', 'False'),
(210, 'Chasseur de Troolls', 'Chasseuse de Troolls', '8', 'False'),
(211, 'Ami des dragons', 'Amie des dragons', '1', 'True');
